/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SimpleCalc;

import my.simplecalc.SimpleCalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SimpleCalc.main(args);
    }
}
